[TWINFACES-58] Edit twinClass link
alcosi/twinfaces pull request #26
Opened 2024-10-21 10:22 UTC by kerim-alcosi

2024-10-23 09:15 UTC, pihaizer requested changes
Please use function instead of const where possible. Consider moving some refactoring (like experimental crud data table) to a separate branch,

2024-10-23 11:41 UTC, kerim-alcosi commented on src/entities/twinClassLink/components/resource-link/resource-link.tsx
> +  data: TwinClass;
check if `data: TwinClass` is valid

2024-10-24 09:38 UTC, kerim-alcosi commented on src/components/base/data-table/data-table.tsx
> +  onRowClick?: (row: TData) => void;
returned `any`

2024-10-24 09:41 UTC, kerim-alcosi commented
> Please use function instead of const where possible.

✅ Done 

> Consider moving some refactoring (like experimental crud data table) to a separate branch,

✅ Excluded refactoring from this PR and moved to draft [PR](https://github.com/alcosi/twinfaces/pull/32) which can be used later in future

2024-10-24 09:42 UTC, kerim-alcosi commented
> Please use function instead of const where possible. Consider moving some refactoring (like experimental crud data table) to a separate branch,

https://github.com/alcosi/twinfaces/pull/26#issuecomment-2434793532

2024-10-25 07:52 UTC, pihaizer approved these changes

2024-10-25 07:52 UTC, merged